name: Create release
run-name: Create release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Install dependencies
        shell: cmd
        env:
          TEMP: ${{ github.workspace }}\.build-temp
          TMP: ${{ github.workspace }}\.build-temp
        run: |
          if not exist "%TEMP%" mkdir "%TEMP%"
          echo TEMP=%TEMP%
          echo TMP=%TMP%
          echo USERPROFILE=%USERPROFILE%
          npm run init

      - name: Build
        shell: cmd
        run: npm run build-binary

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: dist\WindowsMultiTool.exe
          archive: false

      - name: Create release
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $version = (Get-Content -Raw package.json | ConvertFrom-Json).version
          gh release create $version "dist\WindowsMultiTool.exe" --title $version --generate-notes --target $env:GITHUB_SHA
